version: '3.7'
# If you have modifications, put those in docker-compose.override.yml
# See also, https://docs.docker.com/compose/extends/#multiple-compose-files

x-app-defaults: &app-defaults
  # Assign the `PRESS_CONTAINER_TAG` environment variable to use a specific container image.
  # See hub.docker.com/u/openstax/cnx-press or your local registry for available tags.
  image: "openstax/cnx-press:${PRESS_CONTAINER_TAG:-latest}"
  volumes:
    - ./docs:/app/docs:z
    - ./press:/app/press:z
    - ./tests:/app/tests:z
    - ./htmlcov:/app/htmlcov:z
    - ./var:/app/var:z
    - ./bin:/app/bin:z
  environment:
    - SHARED_DIR=/app/var
    - DB_URL=postgresql://rhaptos@db/repository
    - DB_SUPER_URL=postgresql://rhaptos_admin@db/repository
    - AMQP_URL=amqp://guest@rabbitmq:5672//


services:

  rabbitmq:
    image: rabbitmq:latest

  db:
    image: openstax/cnx-db:latest
    # For development usage, use something like the following
    # build:
    #   context: https://github.com/Connexions/cnx-db.git#master
    ports:
      - "15432:5432"
    environment:
      - DB_URL=postgresql://rhaptos@/repository
      - DB_SUPER_URL=postgresql://rhaptos_admin@/repository

  web:
    <<: *app-defaults
    command: gunicorn -b 0.0.0.0:6543 --access-logfile - --error-logfile - -n press --reload wsgi:app --timeout=180
    ports:
      - "88:6543"

  worker:
    <<: *app-defaults
    command: celery -A press worker --beat --loglevel debug
